# **NumPy  Tutorial**
---
İçerik
---

1.   [NumPy Hakkında ve Kurulumu](#1)
2.  [Array Oluşturma (Zeros-Ones-Full-Arange-Linspace-Eye..)](#2)
3.   [Random Arrayler Oluşturma](#3)
4.   [Array Özellikleri (Array Kaydetme, Transpoze..)](#4)
5.   [Yeniden Şekillendirme(Reshaping), Birleştirme(Concatenate), Ayırma(Split), Sıralama(Sorting)](#5)
6.   [Koşullu Eleman İşlemleri](#6)
7.   [Indexlerle Elemanlara Erişim](#7)
8.   [Matematiksel İşlemler](#8)

---



<a id = "1"></a><br>
**NumPy Hakkında ve Kurulum**

***NumPy:*** Açılımı Numerical Python olan NumPy, dizi ve matrisler üzerinde yüksek düzeyde matematiksel işlemler yapmak için oluşturulmuş bir python kütüphanesidir. Python listelerinden çok daha fazla hızlı olan array veri tipine sahiptir. Veri bilimi ve makine öğrenmesi alanlarında çokça kullanılan açık kaynaklı bir yazılımdır.

**Resmi sitesi :** `https://numpy.org/`

In [ ]:
!pip install numpy   #Notebook üzerinde numpy kurulumu

In [ ]:
import numpy as np           #np kısaltması ile numpy içeri aktarıldı

In [ ]:
print(np.__version__)        #Numpy'ın versiyonu

1.19.5


<a id = "2"></a><br>

Array Oluşturma

In [ ]:
array = np.array([1,2,3])    #listeden array oluşturma

In [ ]:
type(array)   #numpy.ndarray

array.dtype   #dtype('int64')

In [ ]:
np.array([1,2,3,4], dtype="float32")  #dtype'ını değiştirebiliriz.

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.ones((3,4))  #Belirtilen size kadar 1'lerden array oluşturur.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros(10)  #Belirtilen size kadar 0'lardan array oluşturur.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.full((2,3), 9) #2v3 'lük 9'lardan oluşan array oluşturur.

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
np.arange(0,10,2) #Pythondaki range fonksiyonudur.

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,1,30) #0-1 arasında 30 adet sayı oluşturur.

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [ ]:
np.eye(3,3)   #Diagonal 1'lerden oluşurken, diğer elemanlar 0'dır.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<a id = "3"></a><br>
**Random Array Oluşturma**

In [ ]:
np.random.random(size= 10) #0.0- 1.0 arasında float random sayılar döner.

array([0.616934  , 0.94374808, 0.6818203 , 0.3595079 , 0.43703195,
       0.6976312 , 0.06022547, 0.66676672, 0.67063787, 0.21038256])

In [ ]:
np.random.randn(10) #Standard normal dağılma sahip random sayılar döner.

array([-0.77576235,  0.99571135, -1.93320478,  0.24853063, -0.03124534,
       -0.13947396, -0.19065598,  0.44863753, -0.99242977, -0.22593966])

In [ ]:
np.random.randint(low= 1, high=20, size=(3,3)) #low-high değerler arasında size kadar random integer sayı üretir.

array([[ 4, 16, 14],
       [17, 18,  6],
       [10,  4,  1]])

In [ ]:
np.random.seed(seed=42)    #üretilen random sayıları sabitlemek için kullanılır. (pseudo-random number generator.)
#seed parametresine istenilen değer verilebilir. Aynı değer verilirse her kodu çalıştıran için aynı random sayılar döner.

In [ ]:
np.random.choice(np.arange(10), size=3) #içine verilen arrayden size kadar random seçim yapar.

array([0, 3, 2])

In [ ]:
ara = np.arange(10)  #sıralı 0-9 sayılar üretildi
np.random.shuffle(ara)   #sıralı sayılar karıştırıldı
ara #son hali

array([9, 0, 6, 4, 5, 3, 8, 1, 2, 7])

**Array Özellikleri**
* ndim: Boyut sayısı
* shape: Boyut bilgisi
* size: Toplam eleman sayısı
* dtype: Array veri tipi

In [ ]:
np.random.seed(seed=0)  #random generator özelliği devre dışı bırakıldı.
arr = np.random.randint(2,20, size=(3,3))
arr

array([[14, 17,  2],
       [ 5,  5,  9],
       [11,  6,  8]])

In [ ]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(3, 3)
9
int64


In [ ]:
#array kaydetme-yükleme
arr = np.arange(10)
np.save('some_array', arr) #some_array ismiyle kaydedildi.
np.load('some_array.npy')  #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
#transpoze
arr = np.arange(32).reshape((8, 4))
arr.T #transpoze alır

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

<a id = "5"></a><br>
**Yeniden Şekillendirme(Reshaping), Birleştirme(Concatenate), Ayırma(Split), Sıralama(Sorting)**

In [ ]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshaping;
arr.reshape(3,3)   #3v3 lük matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a2 = np.array([1,2,3])
a2

array([1, 2, 3])

In [ ]:
a2.ndim

1

In [ ]:
row_vector = a2[np.newaxis, : ]   #satır vektörü oluşturma

In [ ]:
col_vector = a2[:,np.newaxis]     #sütun vektörü oluşturma

In [ ]:
print("Row Vector: {}\nCol Vector:{}".format(row_vector,col_vector))

Row Vector: [[1 2 3]]
Col Vector:[[1]
 [2]
 [3]]


In [ ]:
print("Row_vector ndim : {}\nCol_vector ndim: {}".format(row_vector.ndim, col_vector.ndim))

Row_vector ndim : 2
Col_vector ndim: 2


In [ ]:
#Concatenate;
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
#iki boyutlu;
ar = np.array([[1,2,3],
               [4,5,6]])

In [ ]:
np.concatenate([ar,ar])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([ar,ar], axis=1)    #Column bazında birleştirme işlemi

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#farklı boyutlu arrayleri birleştirme;
x = np.array([1,2,3])
y = np.array([[4,5,6],
              [7,8,9]])

z = np.array([[0],
              [0]])

In [ ]:
np.vstack([x,y])  #vertical stack

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.hstack([y,z])  #horizontal stack

array([[4, 5, 6, 0],
       [7, 8, 9, 0]])

In [ ]:
#Splitting;
t = np.random.randint(1,10,size=7)
t

array([9, 2, 7, 8, 8, 9, 2])

In [ ]:
a,b,c = np.split(t, [2,5])

In [ ]:
print("Sol taraf:{}\nOrta taraf:{}\nSağ Taraf:{}".format(a,b,c))

Sol taraf:[9 2]
Orta taraf:[7 8 8]
Sağ Taraf:[9 2]


In [ ]:
n = np.arange(16).reshape(4,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
ust,alt = np.vsplit(n,[2])      #vertical split
print("Üst taraf:{}\nAlt taraf:{}".format(ust,alt))

Üst taraf:[[0 1 2 3]
 [4 5 6 7]]
Alt taraf:[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
sol,sag = np.hsplit(n,[2])
print("Sol taraf:{}\nSağ taraf:{}".format(sol,sag))

Sol taraf:[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Sağ taraf:[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
#Sorting;
v = np.random.randint(0,30,size=8)
v

#iki boyutlu sıralama için axis argümanı kullanılır.

array([ 5, 25, 13,  8,  9, 20, 19, 16])

In [ ]:
np.sort(v)          #gecici sıralama

array([ 5,  8,  9, 13, 16, 19, 20, 25])

In [ ]:
v.sort()          #kalıcı sıralama

<a id = "6"></a><br>
**Koşullu Eleman İşlemleri**

In [ ]:
arr = np.array([1,2,3,4,5,6])

In [ ]:
arr <3  #3 den kücük olanlar True, eşit ve büyük olanlar False döner.

array([ True,  True, False, False, False, False])

In [ ]:
arr >3

array([False, False, False,  True,  True,  True])

In [ ]:
arr == 3          #3 e eşit olanlar True döner
np.equal(3,arr)   #equal fonksiyonuda kullanılabilir.

array([False, False,  True, False, False, False])

In [ ]:
arr != 3      #3.e eşit olanlar False döner.

array([ True,  True, False,  True,  True,  True])

In [ ]:
arr ** 2        #kare alır.

array([ 1,  4,  9, 16, 25, 36])

In [ ]:
np.sum(arr<4)  #4 den küçük olanların sayısını verir.

3

In [ ]:
(arr >2) & (arr <4)   #2 den büyük 4 den küçük olan True döner.
# % ile sembolüdür, her iki koşuluda sağlaması gerekir.

array([False, False,  True, False, False, False])

In [ ]:
arr[(arr >2) & (arr <4)]  #True dönen değeri görmek için arr içine yazdık.

array([3])

In [ ]:
(arr >2) | (arr <4) # | yada sembolüdür, en az bir koşulu sağlayan değer True döner.

array([ True,  True,  True,  True,  True,  True])

In [ ]:
np.all(arr >2) #Tüm elemanlar koşulu sağlarsa True, sağlamazsa False döner.

False

In [ ]:
np.any(arr <3) #En az bir eleman sağlaması durumunda True, yoksa False döner.

True

<a id = "7"></a><br>
**Indexlerle Elemanlara Erişim**


In [ ]:
h = np.arange(6)
h

array([0, 1, 2, 3, 4, 5])

In [ ]:
#indexler 0'dan başlar
h[0]

0

In [ ]:
h[-1]  #son elemana erişim

5

In [ ]:
#iki boyutlu arraylere erişim
h2 = np.arange(16).reshape(4,4)
h2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#h2[satır,sütun]
h2[0,0]

0

In [ ]:
h2[1,2] 

6

In [ ]:
h2[1,2] = 4.3

In [ ]:
h2[1,2]  #4.3 yazdık fakat 4 olarak tutmuş, çünkü arrayler tek tipde veri tutar.

4

In [ ]:
a = np.arange(10)

In [ ]:
a[::2] #ikişer atlayarak gider.

array([0, 2, 4, 6, 8])

In [ ]:
a[:4] #4.elemana kadar

array([0, 1, 2, 3])

In [ ]:
#h2[start:stop , start:stop]
h2[:,1] #tüm satırları ve sadece 1.sutunu alır

array([ 1,  5,  9, 13])

In [ ]:
h2[1:3,1:2]

array([[5],
       [9]])

In [ ]:
h_copy = h2.copy() 

In [ ]:
h2[0,0] = 999  #orijinal arrayde ki ilk elemanı değiştirdik.

In [ ]:
h_copy[0,0] == h2[0,0]  #Copy aldığımız arrayde değiştirme işlemi olmadı, bu yüzden false döner.

False

<a id = "8"></a><br>
**Matematiksel İşlemler**

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.add(a, 3)     # a + 3
#her elemana 3 ekler

array([3, 4, 5, 6, 7])

In [ ]:
np.subtract(a, 2)  # a-2
#her elemandan 2 çıkarır

array([-2, -1,  0,  1,  2])

In [ ]:
np.multiply(a,4)  #a*4
#her elemanı 4 ile çarpar

array([ 0,  4,  8, 12, 16])

In [ ]:
np.divide(a,2)   # a/2
#her elemanı 2 ile böler

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
np.power(a, 3)  # a **3
#her elemanın kübünü alır

array([ 0,  1,  8, 27, 64])

In [ ]:
#istatistiksel işlemler;
np.mean(a)

2.0

In [ ]:
np.median(a)   

2.0

In [ ]:
np.std(a)     #std: standart deviation

1.4142135623730951

In [ ]:
np.var(a)      #var: varyans

2.0

In [ ]:
np.absolute([-2,-1,0,1,2])  #her elemanın mutlak değerini alır.

array([2, 1, 0, 1, 2])

In [ ]:
np.min(a)

0

In [ ]:
np.max(a)

4